name: orbis_env
channel_priority: strict
channels:
  - pytorch
  - nvidia
  - conda-forge


dependencies:
  # --- Core ---
  - python=3.10
  - pytorch>=2.5
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ffmpeg
  - h5py
  - pip

  # --- Pip packages (no torch/torchvision here to avoid conflicts) ---
  - pip:
      - timm>=1.0
      - diffusers>=0.33
      - accelerate>=1.0
      - einops>=0.7
      - transformers>=4.40
      - datasets>=2.18
      - hydra-core>=1.3
      - omegaconf>=2.3
      - decord>=0.6
      - opencv-python>=4.10
      - pandas>=2.2
      - scikit-learn>=1.4
      - scipy>=1.12
      - tqdm>=4.66
      - submitit>=1.5
      - safetensors>=0.4
      - torchmetrics>=1.3
      - webdataset>=0.2.57
      - pytorch-fid>=0.3.0
      - seaborn>=0.13
      - imageio>=2.34
      - pytorch-lightning>=2.4
      - tensorboard>=2.17
      - albumentations>=2.0
      - msgpack==1.1.2
      - simplejson==3.20.2
      - oauthlib==3.3.1
      - PyJWT==2.10.1
      - lxml==6.0.2
      - chardet==5.2.0
